name: CI  # Name of the workflow

on:
  push:
    branches:
      - main  # Run the workflow on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Define the operating system

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Access the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Update to Python 3.11 to match the project's requirements

    - name: Install Poetry
      run: |
        pip install poetry  # Install Poetry
        poetry --version  # Check Poetry version

    - name: Install dependencies
      run: |
        poetry install  # Install the package and dependencies, including matplotlib

    - name: Build documentation with Sphinx
      run: |
        poetry run sphinx-apidoc -o docs/source src  # Generate .rst files for the package from the src directory
        poetry run sphinx-build -b html docs/source docs/build  # Build HTML documentation directly with sphinx-build
